### ISSUE TITLE
can't use it

### ISSUE THREAD

**Issue by thushalya** [AsyncAPITools/parser-java-wrapper#1]
Can't use this brother..it is not showing under external libraries. @vinodpahuja

**Comment by vinodpahuja** [comment]
I assume you are following steps mentioned in readme and has not missed the local [installation](https://github.com/AsyncAPITools/parser-java-wrapper/blob/main/README.md#installation).

Thanks Brother @thushalya, for using it, share your love by putting a star or fork it if you have any suggestion.

**Comment by thushalya** [comment]
I don't get it..why do I need to have it as a local installation? I was trying to use it as a gradle dependency in my project..so then I just want this to be downloaded through maven central.. can't  you push this to Maven Central and let it be available there to download .... And this is not licensed under Apache license .. therefore my mentor told me not to use this..could you please try to license this under Apache license, so then I can use this one in my project :( @vinodpahuja

**Comment by vinodpahuja** [comment]
Thanks @thushalya for suggestions.
I will try to do it once I get time for the same. 
If you can spare time and want to help, you are welcome.
